//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Escuela
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int ID_Admin { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
        public Nullable<int> Rol_ID { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
