//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Escuela
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Alumnos_Grupos = new HashSet<Alumnos_Grupos>();
        }
    
        public int ID_Grupo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Profesor_ID { get; set; }
        public Nullable<int> Materia_ID { get; set; }
        public Nullable<int> Horario_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos_Grupos> Alumnos_Grupos { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
