//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Escuela
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_AlumnosGrupos
    {
        public int C_ { get; set; }
        public string Grupo { get; set; }
        public int ID_Alumno { get; set; }
        public string Nombre_Alumno { get; set; }
        public int ID_Profesor { get; set; }
        public string Nombre_Profesor { get; set; }
        public string Materia { get; set; }
        public string Horario { get; set; }
    }
}
